from datetime import datetime


def run(state: dict) -> dict:
    """Compile all agent outputs into a structured markdown report."""
    approved = "Yes" if state.get("human_approved") else "Pending"
    generated = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    report = f"""# AI HEDGE FUND INTERN — DUE DILIGENCE REPORT
**Stock:** {state['ticker']} — {state.get('company_name', state['ticker'])}
**Generated:** {generated}

---

## FINANCIAL SNAPSHOT
{state['financial_summary']}

---

## BULL CASE
{state['bull_analysis']}

---

## BEAR CASE
{state['bear_analysis']}

---

## DEBATE REBUTTALS
{state['debate_round']}

---

## RISK AUDIT
{state['risk_audit']}

---

## CIO FINAL VERDICT
{state['judge_verdict']}

---

*Generated by AI Hedge Fund Intern — Multi-Agent Due Diligence System*
*Human Approved: {approved}*
"""
    return {"report": report, "status": "report_done"}
